853502 Maksim Karpov
LilBigStone/Android pull request #1
Opened 2021-01-10 18:36 UTC by LilBigStone

2021-01-10 19:48 UTC, gmltA reviewed
versionName не генерыруецца.

2021-01-10 19:48 UTC, gmltA commented on AmericanChanger/app/src/Premium/java/com/example/americanchanger/MainActivity.java
> +
Дубліруецца код Activity з free версіі.

2021-01-31 08:14 UTC, LilBigStone commented
Maksim Karpov 853502

2021-02-10 17:58 UTC, gmltA requested changes
Вы так і не выправілі заўвагі.

2021-02-11 13:49 UTC, gmltA requested changes
Максім, вы не выправілі падваенне коду.

2021-02-16 12:25 UTC, gmltA requested changes

2021-02-16 12:25 UTC, gmltA commented on AmericanChanger/app/src/main/java/com/example/americanchanger/MainViewModel.java
> +}
І ўся логіка канвертацыі таксама павінна быць тут.

2021-02-16 16:23 UTC, LilBigStone commented
На код без слёз не взглянешь.

2021-02-16 16:23 UTC, closed without merging